using UnityEngine;

/// <summary>
/// Simulates the focal-plane image processing pipeline for the FSOC system.
/// Extracts the raw RGB VirtualCamera output and generates a processed monochrome sensor representation.
/// </summary>
public class SensorProcessor : MonoBehaviour
{
    public enum ProcessingMode
    {
        MonochromeClean,
        MonochromeWithNoise // Hook for future atmospheric/sensor noise, jitter, and platform motion
    }

    [Header("Input Stream")]
    [Tooltip("The raw RGB RenderTexture generated by the VirtualCamera (FSOC_Sensor_RT).")]
    public RenderTexture sourceTexture;

    [Header("Processing Configuration")]
    [Tooltip("The current processing mode applied to the image stream.")]
    public ProcessingMode currentMode = ProcessingMode.MonochromeClean;

    [Tooltip("Material containing a Grayscale conversion shader. If unassigned, the processor falls back to a clean RGB copy.")]
    public Material processingMaterial;

    [Header("Output Stream (Read-Only)")]
    [Tooltip("The final processed sensor image (FSOC_Monochrome_RT) available for BeaconDetector and UI.")]
    public RenderTexture processedTexture;

    private void Start()
    {
        InitializeMaterial();
        InitializeTexture();
    }

    private void InitializeMaterial()
    {
        if (processingMaterial == null)
        {
            Shader shader = Shader.Find("Hidden/FSOC/SensorGrayscale");
            if (shader != null)
            {
                processingMaterial = new Material(shader);
                Debug.Log("[SensorProcessor] Automatically generated processing material using 'Hidden/FSOC/SensorGrayscale' at runtime.");
            }
            else
            {
                Debug.LogError("[SensorProcessor] Failed to find shader 'Hidden/FSOC/SensorGrayscale'. Ensure SensorGrayscale.shader exists, is compiling correctly, and is available.");
            }
        }
    }

    private void InitializeTexture()
    {
        if (sourceTexture == null)
        {
            Debug.LogError("[SensorProcessor] Source Texture is missing! Please assign FSOC_Sensor_RT in the Inspector.", this);
            return;
        }

        // Fetch the configured resolution from the global source of truth to ensure strict dimensional consistency
        int width = PSConfiguration.Instance != null ? PSConfiguration.Instance.SensorWidth : 640;
        int height = PSConfiguration.Instance != null ? PSConfiguration.Instance.SensorHeight : 480;

        // Initialize the output monochrome texture.
        // Creating a distinct texture prevents mutating the VirtualCamera's raw output.
        processedTexture = new RenderTexture(width, height, 0, sourceTexture.format)
        {
            name = "FSOC_Monochrome_RT",
            filterMode = FilterMode.Bilinear,
            wrapMode = TextureWrapMode.Clamp
        };
        processedTexture.Create();
        
        Debug.Log($"[SensorProcessor] Initialized FSOC_Monochrome_RT at {width}x{height}.");
    }

    private void LateUpdate()
    {
        if (sourceTexture == null || processedTexture == null)
            return;

        ProcessSensorImage();
    }

    /// <summary>
    /// Executes the focal-plane image processing pipeline. 
    /// Architecture is isolated here so disturbance effects (jitter, noise) can be layered cleanly later.
    /// </summary>
    private void ProcessSensorImage()
    {
        switch (currentMode)
        {
            case ProcessingMode.MonochromeClean:
                ApplyMonochromeConversion();
                break;
                
            case ProcessingMode.MonochromeWithNoise:
                // TODO: Future Implementation Hook.
                // Layer 1: Apply Platform Motion (Affine Transforms)
                // Layer 2: Apply Camera Jitter (High-frequency offset)
                // Layer 3: Apply Monochrome Conversion
                // Layer 4: Apply Sensor Read Noise (Gaussian) / Dead Pixels
                ApplyMonochromeConversion(); 
                break;
        }
    }

    private void ApplyMonochromeConversion()
    {
        if (processingMaterial != null)
        {
            // Execute fast GPU-based grayscale conversion using the assigned shader
            Graphics.Blit(sourceTexture, processedTexture, processingMaterial);
        }
        else
        {
            // Fallback: direct copy if material is missing, avoiding a pipeline crash.
            // A warning is omitted in the loop to prevent console spam.
            Graphics.Blit(sourceTexture, processedTexture);
        }
    }
}
